version: "3.7"
services:
  storage:
    image: node:16
    command: sh -c "npm install && node ./mysql/index.js"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=database
      - MYSQL_PASS=database_password
  database:
    image: mysql:5.7
    volumes:
      - ocDatabase:/var/lib/mysql
      - ./storage:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=database_password
      - MYSQL_DATABASE=characters-api

volumes:
  ocDatabase: