version: "3.7"
services:
  storage-mysql:
    image: node:16
    command: sh -c "npm install && node ./mysql/index.js"
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST="oc-mysql-database"
      - MYSQL_PASS="database_password"
  oc-mysql-database:
    image: mysql
    volumes:
      - ocDatabase:/var/lib/mysql
      - ./storage:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD="database_password"
      - MYSQL_DATABASE="characters-api"

volumes:
  ocDatabase: